-- migration: create mvp schema for 10x-cards
-- purpose: introduces core enums, tables, constraints, indexes, triggers and rlspolicies for the mvp release.
-- affected objects: enums locale_enum, card_source_enum, card_status_enum;
--                  tables profiles, generations, generation_errors, cards;
--                  functions tr_cards_default_status, tr_cards_update_counters;
--                  policies on all tables as described.
-- special notes: all objects are created with comprehensive comments and granular row-level security. destructive commands are not used in this migration.

-- 1. prerequisites ---------------------------------------------------------------------------
create extension if not exists "pgcrypto"; -- required for gen_random_uuid()

-- 2. enums -----------------------------------------------------------------------------------
create type locale_enum as enum ('pl','en');
create type card_source_enum as enum ('manual','ai_created','ai_edited');
create type card_status_enum as enum ('pending','accepted','rejected');

-- 3. tables ----------------------------------------------------------------------------------
-- 3.1 profiles -------------------------------------------------------------------------------
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  locale locale_enum not null default 'pl',
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

-- 3.2 generations ---------------------------------------------------------------------------
create table public.generations (
  id bigserial primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  prompt_text text not null check (char_length(prompt_text) between 1000 and 10000),
  model text not null,
  model_settings jsonb not null,
  cost_usd numeric(10,4) not null default 0,
  duration_s integer not null default 0,
  total_generated integer not null default 0,
  total_accepted integer not null default 0,
  total_deleted integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.generations enable row level security;

-- 3.3 generation_errors ----------------------------------------------------------------------
create table public.generation_errors (
  id bigserial primary key,
  generation_id bigint not null references public.generations(id) on delete cascade,
  error_code text not null,
  error_message text not null,
  created_at timestamptz not null default now()
);

alter table public.generation_errors enable row level security;

-- 3.4 cards ----------------------------------------------------------------------------------
create table public.cards (
  id bigserial primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  generation_id bigint references public.generations(id) on delete set null,
  deck_id uuid, -- planned future fk to decks
  front varchar(200) not null check (char_length(front) <= 200),
  back varchar(500) not null check (char_length(back) <= 500),
  source card_source_enum not null,
  status card_status_enum not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, front)
);

alter table public.cards enable row level security;

-- 4. indexes ---------------------------------------------------------------------------------
create index if not exists cards_user_idx on public.cards (user_id);
create index if not exists cards_user_source_idx on public.cards (user_id, source);
create index if not exists cards_user_status_idx on public.cards (user_id, status);
create index if not exists cards_generation_idx on public.cards (generation_id);
create index if not exists generations_user_idx on public.generations (user_id);
create index if not exists generation_errors_generation_idx on public.generation_errors (generation_id);

-- 5. triggers --------------------------------------------------------------------------------
-- 5.1 default status trigger -----------------------------------------------------------------
create or replace function public.tr_cards_default_status()
returns trigger language plpgsql as $$
begin
  -- if the card is generated by ai we mark it pending for moderation; otherwise accepted by default
  if new.source = 'ai_created' then
    new.status := 'pending';
  else
    new.status := 'accepted';
  end if;
  return new;
end;$$;

create trigger trg_cards_default_status
before insert on public.cards
for each row execute procedure public.tr_cards_default_status();

-- 5.2 counters trigger ----------------------------------------------------------------------
create or replace function public.tr_cards_update_counters()
returns trigger language plpgsql as $$
begin
  -- recompute counters for the affected generation in a single statement for correctness.
  update public.generations g set
    total_generated = sub.cnt_all,
    total_accepted  = sub.cnt_accepted,
    total_deleted   = sub.cnt_deleted,
    updated_at      = now()
  from (
    select
      c.generation_id as gid,
      count(*)                    as cnt_all,
      count(*) filter (where c.status = 'accepted') as cnt_accepted,
      count(*) filter (where c.status = 'rejected') as cnt_deleted
    from public.cards c
    where c.generation_id = coalesce(new.generation_id, old.generation_id)
    group by c.generation_id
  ) sub
  where g.id = sub.gid;
  return null; -- for after triggers
end;$$;

create trigger trg_cards_update_counters
after insert or update or delete on public.cards
for each row execute procedure public.tr_cards_update_counters();

-- 6. rls policies ---------------------------------------------------------------------------
-- 6.1 profiles ------------------------------------------------------------------------------
-- select only own profile
create policy profiles_select_self on public.profiles
for select using (id = auth.uid());

-- insert profile for self
create policy profiles_insert_self on public.profiles
for insert with check (id = auth.uid());

-- 6.2 generations ----------------------------------------------------------------------------
create policy generations_select_owner on public.generations
for select using (user_id = auth.uid());
create policy generations_insert_owner on public.generations
for insert with check (user_id = auth.uid());
create policy generations_update_owner on public.generations
for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy generations_delete_owner on public.generations
for delete using (user_id = auth.uid());

-- 6.3 generation_errors ----------------------------------------------------------------------
create policy generation_errors_select_owner on public.generation_errors
for select using (generation_id in (select id from public.generations where user_id = auth.uid()));

-- 6.4 cards ----------------------------------------------------------------------------------
create policy cards_select_owner on public.cards
for select using (user_id = auth.uid());
create policy cards_insert_owner on public.cards
for insert with check (user_id = auth.uid());
create policy cards_update_owner on public.cards
for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy cards_delete_owner on public.cards
for delete using (user_id = auth.uid());

-- end of migration ---------------------------------------------------------------------------
